### ISSUE TITLE
adding [taxonomies] section to config.toml causes panic

### ISSUE THREAD

**Issue by nancym** [LiaungYip/plain-blog#1]
First, thanks for this sweet theme! I tried adding a `[taxonomies]` section to config.toml, e.g.:

```
[taxonomies]
    cat = "cats"
```

When I run `hugo server` or `hugo` I get lots of error messages, starting with this:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x9aaa87]
:
```

Do you have any idea what's going on? It seems I don't need a `[taxonomies]` section for the tags and categories plain-blog built-in taxonomies to just work, but I'm trying to learn Hugo and want to do some experiments.

Thank you!

PS - I'm using `Hugo Static Site Generator v0.19 darwin/amd64 BuildDate: 2017-02-27T12:36:32-08:00` and this panic happens on both Mac and Windows.

**Comment by LiaungYip** [comment]
I actually observed the same behaviour while developing the theme. In my case, defining a taxonomy `series = "series"` produced the same crash.

I'm not sure if it's a bug in my theme, or a bug in Hugo itself. It didn't affect my usage so I haven't gotten around to troubleshooting it yet.

Probably a good first step is to see how much of the `plain-blog` theme you can delete, before the bug stops occuring (if at all.)

**Comment by nancym** [comment]
I've done some testing but so far haven't figured out what's causing this crash. I don't even understand why tags and categories work without being specified in a [taxonomies] section of the config.toml file?! If I figure out what's causing this, I'll post here. I'm struggling with understanding the basics of Hugo at this point :crying_cat_face:

**Comment by LiaungYip** [comment]
@nancym judging from the contents of https://www.ii.com/portal/gohugo/ , you have learned **substantially** more about Hugo in the last few years!

I have been doing a bit more work on this theme and have probably fixed this (at least, having a "series" taxonomy works for me now!) Thanks for your attention all those years ago.
