### ISSUE TITLE
Hugo outputs the following message: "WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false."

### ISSUE THREAD

**Issue by fu-sen** [LiaungYip/plain-blog#2]
I am closely watching this message when I am deploying Hugo:
```
> hugo
Building sites … WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
```

This is due to Hugo's specification change:

[SOLVED] {{ isset }} How to check variable is empty?
https://discourse.gohugo.io/t/solved-isset-how-to-check-variable-is-empty/1764

The corresponding code should be modified. The applicable is here:

[**/layouts/partials/header.html**](https://github.com/LiaungYip/plain-blog/blob/master/layouts/partials/header.html)
```
    {{ if isset .Site.Params.header "tagline" }}<p id="tagline">{{ .Site.Params.header.tagline }}</p>{{ end }}
```
Probably it can be improved with this code:
```
    {{ if .Site.Params.header.tagline }}<p id="tagline">{{ .Site.Params.header.tagline }}</p>{{ end }}
```

**Comment by LiaungYip** [comment]
Thanks; this is fixed in https://github.com/LiaungYip/plain-blog/commit/578b7ceaaa3922b2d54291db688d8c3fc24df5c1 .
